#! @Chapter Combinatorial structures 

#! @Section Posets

#! @Description
#!  Category of posets. 
DeclareCategory( "IsPoset", IsObject and IsAttributeStoringRep );

#!
DeclareRepresentation( "IsPosetRep", IsPoset, 
        [ "set", "binary_relation", "minimal_relations", "lessthan" ] );

#! @Description
#!  Returns the poset defined on the points  <A>_P</A>  and the relations 
#!  generated by  <A>_rel</A>.  The elements in  <A>_P</A>  is given as a list, for
#!  example <C>["a", "b", "c", "d"]</C> and the relations are given as a list of 
#!  lists, for instance in the above case:  <C>[ ["a", "b", "c"], ["b", "d"], 
#!  ["c", "d"] ].</C> The first list means that <C>"a" < "b"</C> and <C>"a" < "c"</C>,  and
#!  the second one means <C>"b" < "d"</C>  and finally the last one means 
#!  <C>"c" < "d".</C> 
#! @Returns <Ref Filt="IsPoset"/>
#! @Arguments _P, _rel
DeclareOperation( "Poset", [ IsList, IsList ] );

#! @Description
#!  Returns the number of elements in a poset.
#! @Return <C>IS_INT</C>
#! @Arguments P
DeclareAttribute( "Size", IsPoset );

#! @Description
#!  Returns the underlying set of a poset.
#! @Return <C>IsSet</C>
#! @Arguments P
DeclareOperation( "UnderlyingSet", [ IsPoset ] );

#! @Description
#!  Returns the partial order of a poset. That is, a function <M>\rho\colon 
#!  P\times P \to \{ \textrm{true, false}\}</M>, where <M>\rho( a, b) = \textrm{true}</M>
#!  if <M>a \leq b</M> and false otherwise. 
#! @Return <C>IsBool</C>
#! @Arguments P
DeclareOperation( "PartialOrderOfPoset", [ IsPoset ] );

BindGlobal( "TheFamilyOfPosets", NewFamily( "TheFamilyOfPosets" ) );
BindGlobal( "TheTypePoset", NewType( TheFamilyOfPosets, IsPosetRep ) );

#